apiVersion: dapr.io/v1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: 192.168.10.205:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"
